### ISSUE TITLE
mainwindow_gen

### ISSUE THREAD

**Issue by ns-mkusper** [switchbrew/nxdbg#1]
This mainwindow_gen file supposed to be empty? Not totally familiar with Qt UI programming but I'm getting missing methods:

`~/github/nxdbg/debugger (master) $ make
python2 MainWindow.py
Traceback (most recent call last):
  File "MainWindow.py", line 47, in <module>
    class MainDebugger(QtGui.QMainWindow, mainwindow_gen.Ui_MainWindow):
AttributeError: 'module' object has no attribute 'Ui_MainWindow'
make: *** [all] Error 1`

**Comment by plutooo** [comment]
You need to run "make" once
